# Generated by Django 6.0.5 on 2026-05-09 01:39

from django.db import migrations, models
import django.conf
import cloudinary.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.CASCADE, related_name='photos', to=django.conf.settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
