# Generated by Django 6.0.5 on 2026-05-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_add_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipephoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/'),
        ),
    ]
